# Generated by Django 3.1.7 on 2021-03-29 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.CharField(blank=True, max_length=500)),
                ('project_role', models.CharField(max_length=100)),
                ('skills_used1', models.CharField(blank=True, max_length=500)),
                ('skills_used2', models.CharField(blank=True, max_length=500)),
                ('skills_used3', models.CharField(blank=True, max_length=500)),
                ('skills_used4', models.CharField(blank=True, max_length=500)),
                ('skills_used5', models.CharField(blank=True, max_length=500)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
