# Generated by Django 3.1.7 on 2021-03-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('organised', models.BooleanField(default=False)),
                ('stubborn', models.BooleanField(default=False)),
                ('introvert', models.BooleanField(default=False)),
                ('extrovert', models.BooleanField(default=False)),
                ('agreeable', models.BooleanField(default=False)),
                ('passive', models.BooleanField(default=False)),
                ('creative', models.BooleanField(default=False)),
                ('unpredictable', models.BooleanField(default=False)),
                ('neurotic', models.BooleanField(default=False)),
                ('versatility', models.BooleanField(default=False)),
                ('regularity', models.BooleanField(default=False)),
                ('efficiency', models.BooleanField(default=False)),
                ('teamwork', models.BooleanField(default=False)),
                ('memory', models.BooleanField(default=False)),
                ('psa', models.BooleanField(default=False)),
                ('business', models.BooleanField(default=False)),
                ('management', models.BooleanField(default=False)),
                ('technical', models.BooleanField(default=False)),
                ('entrepreneur', models.BooleanField(default=False)),
                ('path_finding', models.BooleanField(default=False)),
                ('space', models.BooleanField(default=False)),
                ('data_handling', models.BooleanField(default=False)),
            ],
        ),
    ]
