# Generated by Django 3.1.7 on 2021-03-22 15:42

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_suggested_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggested_subject',
            name='suggested_subjects',
            field=jsonfield.fields.JSONField(),
        ),
    ]
