# Generated by Django 3.1.7 on 2021-03-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20210322_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggested_subject',
            name='suggested_subjects',
            field=models.CharField(max_length=500),
        ),
    ]
