# Generated by Django 3.1.7 on 2021-05-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_auto_20210515_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='career',
            field=models.CharField(default='IT', max_length=50),
        ),
    ]
