# Generated by Django 3.1.7 on 2021-03-19 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.IntegerField(default=0)),
                ('question_2', models.IntegerField(default=0)),
                ('question_3', models.IntegerField(default=0)),
                ('question_4', models.IntegerField(default=0)),
                ('question_5', models.IntegerField(default=0)),
                ('question_6', models.IntegerField(default=0)),
                ('question_7', models.IntegerField(default=0)),
                ('question_8', models.IntegerField(default=0)),
                ('question_9', models.IntegerField(default=0)),
                ('question_10', models.IntegerField(default=0)),
                ('employbility_score', models.IntegerField(default=0)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
