# Generated by Django 3.1.7 on 2021-03-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('init_test', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='score',
        ),
    ]
