# Generated by Django 3.1.7 on 2021-03-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_test', '0005_student_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_score',
            old_name='Technical',
            new_name='entrepreneur',
        ),
        migrations.AddField(
            model_name='student_score',
            name='technical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student_score',
            name='versatility',
            field=models.BooleanField(default=False),
        ),
    ]
