# Generated by Django 3.1.7 on 2021-03-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_test', '0006_auto_20210320_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_score',
            name='data_handling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student_score',
            name='path_finding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student_score',
            name='space',
            field=models.BooleanField(default=False),
        ),
    ]
