# Generated by Django 3.1.7 on 2021-05-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_test', '0007_auto_20210327_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='option3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='option4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
